* 1008 Elevator（20 分）
The highest building in our city has only one elevator. A request list is made up with N positive numbers. The numbers denote at which floors the elevator will stop, in specified order. It costs 6 seconds to move the elevator up one floor, and 4 seconds to move down one floor. The elevator will stay for 5 seconds at each stop.

For a given request list, you are to compute the total time spent to fulfill the requests on the list. The elevator is on the 0th floor at the beginning and does not have to return to the ground floor when the requests are fulfilled.

** Input Specification:
Each input file contains one test case. Each case contains a positive integer N, followed by N positive numbers. All the numbers in the input are less than 100.

** Output Specification:
For each test case, print the total time on a single line.

** Sample Input:
#+BEGIN_SRC text
3 2 3 1
#+END_SRC
** Sample Output:
#+BEGIN_SRC text
41
#+END_SRC
** Analyzation
简单模拟电梯上下行，计算时间花费
** Solutions
#+BEGIN_SRC c++
#include <cstdio>
int main() {
  int eposi = 0, n, stime = 0;
  scanf("%d", &n);
  for(int i=1; i<=n; i++){
    int floor;
    scanf("%d", &floor);
    floor -= eposi;
    if(floor>=0) stime += floor*6+5;
    else stime += -floor*4+5;
    eposi += floor;
  }
  printf("%d", stime);
  return 0;
}
#+END_SRC
